Add winston-loki support
NodeFactoryIo/node-ts-starter-fastify pull request #12
Opened 2020-08-21 07:33 UTC by nmlinaric

Add winston-loki support + winston-loki typings.

Resolves #7

2020-08-21 07:40 UTC, mpetrunic commented
@nmlinaric What's your issue?

2020-08-21 07:41 UTC, mpetrunic commented on @types/winston-loki/index.d.ts
> +import * as Transport from "winston-transport";
import must be inside declare module

2020-08-21 07:42 UTC, mpetrunic commented on @types/winston-loki/index.d.ts
> +    export class LokiTransport extends Transport {
```suggestion
    export class LokiTransport extends Transport.TransportStream {
```

2020-08-21 07:44 UTC, nmlinaric commented
> @nmlinaric What's your issue?

Not 100% sure if `winston-loki` typings are ok this way and having trouble with that `TransportStream`

2020-08-21 08:33 UTC, mpetrunic commented on .env.sample
> +LOKI_LOGGING=false;
```suggestion
WINSTON_LOKI_URL=http://localhost:3000;
```
If not set don't add transport

2020-08-21 08:39 UTC, mpetrunic commented on src/services/logger/index.ts
> +    host: "http://localhost:3100",
you should pass custom labels.

I think we are suing "label" as moduleName

2020-08-25 07:03 UTC, nmlinaric commented
@mpetrunic I've added `GRAFANA_CONTAINER_NAME`, `GRAFANA_CONTAINER_PORT`, `WINSTON_LOKI_CONTAINER_NAME`, `WINSTON_LOKI_CONTAINER_PORT` `env` variables for setting them on the server in containers, are we going to need them or are they excess?

2020-08-25 07:14 UTC, mpetrunic requested changes

2020-08-25 07:14 UTC, mpetrunic commented on src/services/logger/index.ts
> +      level: process.env.WINSTON_LOKI_LEVEL
nope, it has to be level set in message, not just hardcoded one

2020-08-25 07:14 UTC, mpetrunic commented on src/services/logger/index.ts
> +      module: process.env.WINSTON_LOKI_MODULE,
it has to be module attached to winston not env

2020-08-25 07:14 UTC, mpetrunic commented on src/services/logger/index.ts
>      label: "default"
if you rename this to module and remove those static labels it might work out of box

2020-08-25 07:36 UTC, mpetrun5 commented
We are missing error logs here: https://github.com/NodeFactoryIo/node-ts-starter-fastify/blob/816798ce86cb1a19d7165bd1c8dbae6b3ef4a37c/src/services/logger/fastify.ts#L30.
Should be like this: https://github.com/NodeFactoryIo/aument-backend/blob/43fca025aeaf4dd2f8494231c5b2e451ad649422/src/services/logger/fastify.ts#L34

2020-08-26 13:30 UTC, mpetrunic requested changes
Look good, few more comments and you can start integrating this in HP project (maybe you can merge it since they have same base commits)

2020-08-26 13:30 UTC, mpetrunic commented on .env.sample
> +WINSTON_LOKI_URL=http://loki:3100
keep it empty in sample, so it  doesn't attempt to send it locally by default

2020-08-26 13:30 UTC, mpetrunic commented on .env.sample
> +METRICS_IP_WHITELIST=127.0.0.1,127.0.0.2
let it be * by default

2020-08-26 13:30 UTC, mpetrunic commented on src/services/logger/index.ts
> +    batching: false,
env variable

2020-08-26 15:07 UTC, mpetrunic approved these changes

2020-08-26 15:07 UTC, merged